import os
import pygame
import numpy as np
import math
import sys
import argparse
import scipy.ndimage
from planners import AStarPlanner, RRTPlanner

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 30, 30) # Bright neon red for obstacles
GREEN = (0, 255, 0)
BLUE = (0, 150, 255)
ORANGE = (255, 165, 0)
YELLOW = (255, 255, 0)
DARK_GRAY = (40, 40, 40)
LIGHT_GRAY = (200, 200, 200)
MAGENTA = (255, 0, 255)

def normalize_costmap(costmap):
    norm = np.clip(costmap, 0, 1)
    norm = np.nan_to_num(norm, nan=1.0)
    return norm

def check_sensor(rover_pos, path, current_idx, new_costmap, lookahead_dist=40):
    for i in range(current_idx, min(current_idx + lookahead_dist, len(path))):
        p = path[i]
        x, y = int(p[0]), int(p[1])
        if y < 0 or y >= new_costmap.shape[0] or x < 0 or x >= new_costmap.shape[1]:
            continue
        if new_costmap[y, x] >= 0.8:
            return True, i
    return False, -1

def draw_text(surface, text, font, color, x, y):
    text_obj = font.render(text, True, color)
    surface.blit(text_obj, (x, y))

def draw_text_centered(surface, text, font, color, rect):
    text_obj = font.render(text, True, color)
    text_rect = text_obj.get_rect(center=rect.center)
    surface.blit(text_obj, text_rect)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("baseline_map")
    parser.add_argument("new_map")
    args = parser.parse_args()

    baseline_map = np.load(args.baseline_map)
    new_map = np.load(args.new_map)
    rows, cols = baseline_map.shape

    # Optional telemetry layers (if generated by src/cost_map.py)
    slope_map = None
    roughness_map = None
    baseline_dir = os.path.dirname(args.baseline_map)
    slope_path = os.path.join(baseline_dir, "slope.npy")
    roughness_path = os.path.join(baseline_dir, "roughness.npy")
    if os.path.exists(slope_path):
        slope_map = np.load(slope_path)
    if os.path.exists(roughness_path):
        roughness_map = np.load(roughness_path)
    
    # Scale map for comfortable visualization size
    max_dim = max(rows, cols)
    scale = 1.0
    if max_dim > 800:
        scale = 800.0 / max_dim
        baseline_map = scipy.ndimage.zoom(baseline_map, scale, order=0)
        new_map = scipy.ndimage.zoom(new_map, scale, order=0)
        if slope_map is not None:
            slope_map = scipy.ndimage.zoom(slope_map, scale, order=0)
        if roughness_map is not None:
            roughness_map = scipy.ndimage.zoom(roughness_map, scale, order=0)
        rows, cols = baseline_map.shape
    elif max_dim < 700:
        # Upscale small maps so simulation is not tiny on screen
        scale = 700.0 / max_dim
        baseline_map = scipy.ndimage.zoom(baseline_map, scale, order=0)
        new_map = scipy.ndimage.zoom(new_map, scale, order=0)
        if slope_map is not None:
            slope_map = scipy.ndimage.zoom(slope_map, scale, order=0)
        if roughness_map is not None:
            roughness_map = scipy.ndimage.zoom(roughness_map, scale, order=0)
        rows, cols = baseline_map.shape

    # UI Panel Settings
    panel_width = 420
    panel_inner_w = panel_width - 30
    window_width = cols + panel_width
    # Keep a taller window so right panel sections never overlap
    window_height = max(rows, 920)

    pygame.init()
    try:
        screen = pygame.display.set_mode((window_width, window_height))
        pygame.display.set_caption("Lunar Rover Navigation Simulator - Interactive")
        has_display = True
    except pygame.error:
        print("Warning: No display found. Pygame will run headlessly.")
        has_display = False
        screen = None

    clock = pygame.time.Clock()
    font_large = pygame.font.SysFont('Arial', 24, bold=True)
    font_medium = pygame.font.SysFont('Arial', 18, bold=True)
    font_small = pygame.font.SysFont('Arial', 14)

    # Prepare background map
    def build_surface(b_map, n_map):
        surf = pygame.Surface((cols, rows))
        d_map = normalize_costmap(n_map)
        grid_step = 3
        
        for y in range(rows):
            for x in range(cols):
                cost = d_map[y, x]
                
                # Eğer sonradan dinamik engel eklendiyse (Parlak Kırmızı)
                if n_map[y, x] >= 0.8 and b_map[y, x] < 0.8:
                    base = (180, 0, 180)  # final-v1 dynamic obstacle color
                else:
                    # final-v1 ile aynı cost renkleri
                    if np.isnan(n_map[y, x]):
                        base = (40, 40, 40)
                    elif cost >= 1.0:
                        base = (255, 0, 0)
                    elif cost >= 0.6:
                        base = (255, 100, 0)
                    elif cost >= 0.3:
                        base = (200, 200, 0)
                    else:
                        base = (0, 180, 0)

                # final-v1 benzeri piksel-grid görünümü
                if (x % grid_step == 0) or (y % grid_step == 0):
                    color = (max(0, int(base[0] * 0.35)), max(0, int(base[1] * 0.35)), max(0, int(base[2] * 0.35)))
                else:
                    color = base

                surf.set_at((x, y), color)
        return surf

    surface_bg = build_surface(baseline_map, new_map)
    astar = AStarPlanner(baseline_map, obstacle_threshold=0.8)
    rrt = RRTPlanner(new_map, obstacle_threshold=0.8, step_size=8.0, max_iter=3000)

    # Baslangic pozisyonu
    sx, sy = 20, 20
    while sx < cols and baseline_map[sy, sx] >= 0.8:
        sx += 5; sy += 5
    
    gx, gy = cols - 20, rows - 20

    logs = ["System initialized.", "Baseline map loaded.", "Obstacles injected."]
    def add_log(msg):
        print(msg)
        logs.append(msg)
        if len(logs) > 15:
            logs.pop(0)

    state = "AWAITING_TARGET" # AWAITING_TARGET, MOVING, REPLANNING, REACHED, FAILED
    
    global_path = []
    current_path = []
    rover_idx = 0
    running = True
    rrt_paths = []
    
    # ENERGY/BATTERY MECHANIC (realistic baseline + mission budget)
    # Typical rolling energy for planetary rovers can be ~20-60 Wh/km on flat terrain,
    # which is 0.02 - 0.06 Wh per meter, depending on mass/soil/drive train.
    # Use a more realistic battery budget so depletion is not unrealistically fast.
    max_energy_wh = 1200.0
    current_energy = max_energy_wh
    aggressive_mode = False
    
    # 1 pixel in our 1.5m DEM represents 1.5 meters.
    # Distance in meters = pixels * 1.5
    pixel_to_meters = 1.5
    
    # Base energy consumption on flat terrain (faster depletion for demo)
    wh_per_meter_flat = 0.08

    # Keep executed trajectory visible even when battery is empty
    executed_trail = []

    replanning_timer = 0
    local_goal_idx = 0
    obs_rx, obs_ry = 0, 0
    rx, ry = sx, sy 
    
    click_mode = "GOAL" 
    btn_start_rect = pygame.Rect(cols + 15, 310, 180, 35) # New SET START button
    btn_goal_rect = pygame.Rect(cols + 210, 310, 180, 35)
    btn_obs_rect = pygame.Rect(cols + 15, 355, panel_inner_w, 35) # ADD OBSTACLE moved down
    btn_reset_rect = pygame.Rect(cols + 15, 400, panel_inner_w, 35)

    add_log("Awaiting Initial Target. Click SET TARGET.")

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.MOUSEBUTTONDOWN and has_display:
                mx, my = event.pos
                if btn_start_rect.collidepoint(mx, my):
                    click_mode = "START"
                    add_log("Mode: SET START POINT selected.")
                elif btn_obs_rect.collidepoint(mx, my):
                    click_mode = "OBSTACLE"
                    add_log("Mode: ADD OBSTACLE selected.")
                elif btn_goal_rect.collidepoint(mx, my):
                    click_mode = "GOAL"
                    add_log("Mode: SET TARGET selected.")
                elif btn_reset_rect.collidepoint(mx, my):
                    add_log("SYSTEM RESET. Returning to start.")
                    state = "AWAITING_TARGET"
                    global_path, current_path, rrt_paths = [], [], []
                    rover_idx = 0
                    rx, ry = sx, sy
                    current_energy = max_energy_wh
                    aggressive_mode = False
                    executed_trail = []
                elif mx < cols: # Clicked on the map
                    if click_mode == "START":
                        if new_map[my, mx] >= 0.8:
                            add_log("Invalid Start! Cannot spawn on obstacle.")
                        else:
                            sx, sy = mx, my
                            rx, ry = sx, sy
                            state = "AWAITING_TARGET"
                            global_path, current_path, rrt_paths = [], [], []
                            rover_idx = 0
                            current_energy = max_energy_wh
                            aggressive_mode = False
                            executed_trail = []
                            add_log(f"Rover teleported to ({sx}, {sy}).")
                    elif click_mode == "OBSTACLE":
                        r = 25 
                        for y in range(max(0, my-r), min(rows, my+r)):
                            for x in range(max(0, mx-r), min(cols, mx+r)):
                                if (x - mx)**2 + (y - my)**2 <= r**2:
                                    new_map[y, x] = 1.0
                                    surface_bg.set_at((x, y), (180, 0, 180))
                        add_log(f"Obstacle deployed at ({mx}, {my})")
                    elif click_mode == "GOAL":
                        gx, gy = mx, my
                        add_log(f"New Target Locked: ({gx}, {gy})")
                        add_log("Calculating Secure Route (A*)...")
                        
                        _rx, _ry = (int(current_path[rover_idx][0]), int(current_path[rover_idx][1])) if current_path else (rx, ry)
                        # A*'a inanılmaz yüksek bir safety_weight (Güvenlik Ağırlığı) göndererek 
                        # engebeli yolları (cost'u 0.1'den büyük olan) devasa bir maliyetmiş gibi gösteriyoruz.
                        # Böylece kısa değil "En Düz ve En Güvenli" yoldan gidecek.
                        new_global = astar.plan((_rx, _ry), (gx, gy), safety_weight=50.0)
                        
                        if new_global:
                            global_path = new_global
                            current_path = list(global_path)
                            rover_idx = 0
                            rrt_paths = []
                            state = "MOVING"
                            current_energy = max_energy_wh
                            aggressive_mode = False
                            executed_trail = []
                            add_log("Secure Path Established! Rover moving.")
                        else:
                            add_log("ERROR: Target unreachable (A* Failed).")

        if not has_display:
            break

        screen.blit(surface_bg, (0, 0))

        # --- UI PANEL DRAWING ---
        pygame.draw.rect(screen, (22, 22, 22), (cols, 0, panel_width, window_height))
        pygame.draw.rect(screen, DARK_GRAY, (cols + 8, 8, panel_width - 16, window_height - 16), border_radius=8)
        pygame.draw.line(screen, WHITE, (cols, 0), (cols, window_height), 2)
        
        draw_text(screen, "MISSION CONTROL", font_large, WHITE, cols + 15, 20)
        draw_text(screen, "------------------------------", font_medium, WHITE, cols + 15, 45)
        
        # Determine status color
        if state == "MOVING": status_color = GREEN
        elif state == "REPLANNING": status_color = ORANGE
        elif state == "REACHED": status_color = BLUE
        elif state == "AWAITING_TARGET": status_color = YELLOW
        elif state == "BATTERY_EMPTY": status_color = RED
        else: status_color = RED
            
        draw_text(screen, f"STATUS: {state}", font_large, status_color, cols + 15, 70)
        
        if len(current_path) > 0 and rover_idx < len(current_path):
            rx, ry = int(current_path[rover_idx][0]), int(current_path[rover_idx][1])
            
        draw_text(screen, f"Position: X={rx}, Y={ry}", font_medium, LIGHT_GRAY, cols + 15, 100)
        
        # --- BATTERY UI ---
        fuel_pct = max(0.0, current_energy / max_energy_wh)
        draw_text(screen, f"BATTERY: {int(fuel_pct * 100)}% ({int(current_energy)} Wh)", font_medium, WHITE, cols + 15, 135)
        
        fuel_bar_bg = pygame.Rect(cols + 15, 160, panel_inner_w, 15)
        fuel_bar_fg = pygame.Rect(cols + 15, 160, int(panel_inner_w * fuel_pct), 15)
        
        pygame.draw.rect(screen, (80, 80, 80), fuel_bar_bg)
        if fuel_pct > 0.5:
            f_color = (50, 200, 50)
        elif fuel_pct > 0.25:
            f_color = (200, 200, 50)
        else:
            f_color = (200, 50, 50)
            
        pygame.draw.rect(screen, f_color, fuel_bar_fg)
        
        if aggressive_mode:
            draw_text(screen, "LOW BATTERY! DIRECT ROUTING ON", font_small, RED, cols + 15, 180)

        # --- Local Terrain Telemetry (current cell) ---
        cell_x, cell_y = int(rx), int(ry)
        if 0 <= cell_y < new_map.shape[0] and 0 <= cell_x < new_map.shape[1]:
            cur_cost = float(new_map[cell_y, cell_x]) if not np.isnan(new_map[cell_y, cell_x]) else float("nan")
        else:
            cur_cost = float("nan")

        if slope_map is not None and 0 <= cell_y < slope_map.shape[0] and 0 <= cell_x < slope_map.shape[1]:
            cur_slope = float(slope_map[cell_y, cell_x]) if not np.isnan(slope_map[cell_y, cell_x]) else float("nan")
        else:
            cur_slope = float("nan")

        if roughness_map is not None and 0 <= cell_y < roughness_map.shape[0] and 0 <= cell_x < roughness_map.shape[1]:
            cur_rough = float(roughness_map[cell_y, cell_x]) if not np.isnan(roughness_map[cell_y, cell_x]) else float("nan")
        else:
            cur_rough = float("nan")

        draw_text(screen, f"Slope: {cur_slope:.2f} deg" if not np.isnan(cur_slope) else "Slope: N/A", font_small, LIGHT_GRAY, cols + 15, 205)
        draw_text(screen, f"Roughness: {cur_rough:.2f} m" if not np.isnan(cur_rough) else "Roughness: N/A", font_small, LIGHT_GRAY, cols + 15, 223)
        draw_text(screen, f"Cost: {cur_cost:.3f}" if not np.isnan(cur_cost) else "Cost: N/A", font_small, LIGHT_GRAY, cols + 15, 241)

        # Interactive Buttons
        draw_text(screen, "INTERACTION MODE:", font_medium, WHITE, cols + 15, 270)
        
        start_color = (100, 100, 200) if click_mode == "START" else (80, 80, 80)
        goal_color = (50, 150, 50) if click_mode == "GOAL" else (80, 80, 80)
        obs_color = (200, 50, 50) if click_mode == "OBSTACLE" else (80, 80, 80)
        
        # Y eksenlerini fuel barına yer açmak için biraz daha aşağı aldım
        btn_start_rect.y = 300
        btn_goal_rect.y = 300
        btn_obs_rect.y = 345
        btn_reset_rect.y = 390
        
        pygame.draw.rect(screen, start_color, btn_start_rect, border_radius=5)
        pygame.draw.rect(screen, WHITE, btn_start_rect, 2, border_radius=5)
        draw_text_centered(screen, "SET START", font_medium, WHITE, btn_start_rect)

        pygame.draw.rect(screen, goal_color, btn_goal_rect, border_radius=5)
        pygame.draw.rect(screen, WHITE, btn_goal_rect, 2, border_radius=5)
        draw_text_centered(screen, "SET TARGET", font_medium, WHITE, btn_goal_rect)
        
        pygame.draw.rect(screen, obs_color, btn_obs_rect, border_radius=5)
        pygame.draw.rect(screen, WHITE, btn_obs_rect, 2, border_radius=5)
        draw_text_centered(screen, "ADD DYNAMIC OBSTACLE", font_medium, WHITE, btn_obs_rect)

        # RESET Button
        pygame.draw.rect(screen, (150, 50, 50), btn_reset_rect, border_radius=5)
        pygame.draw.rect(screen, WHITE, btn_reset_rect, 2, border_radius=5)
        draw_text_centered(screen, "RESET ROVER", font_medium, WHITE, btn_reset_rect)

        # Draw legend
        draw_text(screen, "LEGEND:", font_medium, WHITE, cols + 15, 440)
        pygame.draw.line(screen, BLUE, (cols + 15, 470), (cols + 45, 470), 2)
        draw_text(screen, "Global Path (A*)", font_small, LIGHT_GRAY, cols + 55, 462)
        
        pygame.draw.line(screen, GREEN, (cols + 15, 490), (cols + 45, 490), 2)
        draw_text(screen, "Active Executed Path", font_small, LIGHT_GRAY, cols + 55, 482)
        
        pygame.draw.line(screen, ORANGE, (cols + 15, 510), (cols + 45, 510), 3)
        draw_text(screen, "Avoidance Path (RRT)", font_small, LIGHT_GRAY, cols + 55, 502)
        
        pygame.draw.rect(screen, RED, (cols + 15, 525, 30, 15))
        draw_text(screen, "Dynamic Obstacle", font_small, LIGHT_GRAY, cols + 55, 525)

        pygame.draw.rect(screen, (0, 180, 0), (cols + 15, 548, 30, 12))
        draw_text(screen, "Safe (low cost)", font_small, LIGHT_GRAY, cols + 55, 545)
        pygame.draw.rect(screen, (200, 200, 0), (cols + 15, 565, 30, 12))
        draw_text(screen, "Medium cost", font_small, LIGHT_GRAY, cols + 55, 562)
        pygame.draw.rect(screen, (255, 100, 0), (cols + 15, 582, 30, 12))
        draw_text(screen, "High cost", font_small, LIGHT_GRAY, cols + 55, 579)
        pygame.draw.rect(screen, (255, 0, 0), (cols + 15, 599, 30, 12))
        draw_text(screen, "Blocked terrain", font_small, LIGHT_GRAY, cols + 55, 596)

        # Draw Logs (auto-scroll and fit panel height)
        legend_bottom_y = 620
        logs_title_y = max(legend_bottom_y + 16, window_height - 250)
        draw_text(screen, "EVENT LOGS:", font_medium, WHITE, cols + 15, logs_title_y)
        line_h = 18
        logs_start_y = logs_title_y + 28
        max_lines = max(1, (window_height - logs_start_y - 12) // line_h)
        visible_logs = logs[-max_lines:]
        for i, log in enumerate(visible_logs):
            draw_text(screen, log, font_small, (150, 255, 150), cols + 15, logs_start_y + (i * line_h))

        # --- MAP DRAWING ---
        if len(global_path) > 1:
            pygame.draw.lines(screen, BLUE, False, global_path, 1) # Global in Blue
        if len(current_path) > 1:
            pygame.draw.lines(screen, GREEN, False, current_path, 2) # Actual path in Green
        for rp in rrt_paths:
            if len(rp) > 1:
                pygame.draw.lines(screen, ORANGE, False, rp, 3) # Local RRT in Orange

        if len(executed_trail) > 1:
            pygame.draw.lines(screen, GREEN, False, executed_trail, 1)

        # Start and Goal Markers
        pygame.draw.circle(screen, MAGENTA, (sx, sy), 6) # Start point is MAGENTA
        
        if state != "AWAITING_TARGET" or click_mode == "GOAL":
            pygame.draw.circle(screen, RED, (gx, gy), 6)
            pygame.draw.line(screen, WHITE, (gx-8, gy-8), (gx+8, gy+8), 2)
            pygame.draw.line(screen, WHITE, (gx-8, gy+8), (gx+8, gy-8), 2)

        # Rover Logic
        if state == "MOVING":
            if rover_idx < len(current_path) - 1:
                pygame.draw.circle(screen, YELLOW, (rx, ry), 5)
                
                # Check sensor
                obs_detected, obs_idx = check_sensor((rx, ry), current_path, rover_idx, new_map, 50)
                
                # Calculate terrain cost for battery consumption
                # current_path is a list of (x,y)
                cur_x, cur_y = int(current_path[rover_idx][0]), int(current_path[rover_idx][1])
                next_x, next_y = int(current_path[rover_idx+1][0]), int(current_path[rover_idx+1][1])
                
                # dist is about 1 for straight, 1.414 for diag (in pixels)
                dist_px = math.hypot(next_x - cur_x, next_y - cur_y)
                dist_m = dist_px * pixel_to_meters
                
                t_cost = new_map[cur_y, cur_x] if not np.isnan(new_map[cur_y, cur_x]) else 0.0
                
                # Decrease battery based on real-world physics approximations:
                # Flat ground: base Wh per meter
                # Slopes exponentially increase energy due to gravity and wheel slip in regolith
                # If t_cost is 0.5 (steep slope), energy could be 10x higher
                slope_penalty_factor = 1.0 + (t_cost * 20.0)
                energy_burn = dist_m * wh_per_meter_flat * slope_penalty_factor
                
                current_energy -= energy_burn

                executed_trail.append((rx, ry))
                if len(executed_trail) > 5000:
                    executed_trail.pop(0)

                if current_energy <= 0:
                    current_energy = 0
                    state = "BATTERY_EMPTY"
                    add_log("BATTERY EMPTY! Rover stopped.")
                    continue
                
                if current_energy < (max_energy_wh * 0.3) and not aggressive_mode:
                    aggressive_mode = True
                    add_log("LOW BATTERY! Engaging Direct Routing.")
                    add_log("Prioritizing distance over safety.")
                    
                    # Replan aggressively from current position to global goal
                    _rx, _ry = rx, ry
                    # Agresif modda "safety_weight" sadece 0.5'e çekiliyor, yani rover engebeye hiç bakmıyor! Direkt dalıyor.
                    new_global = astar.plan((_rx, _ry), (gx, gy), safety_weight=0.5, max_danger=0.95)
                    
                    if new_global:
                        global_path = new_global
                        current_path = list(global_path)
                        rover_idx = 0
                        rrt_paths = []
                        add_log("Aggressive A* Path Established!")
                    else:
                        add_log("Aggressive replanning failed.")
                        
                if obs_detected:
                    state = "REPLANNING"
                    obs_rx, obs_ry = rx, ry
                    add_log(f"ALERT! Unknown obstacle detected.")
                    add_log("Halting. Initializing RRT solver...")
                    
                    local_goal_idx = obs_idx
                    clear = 0
                    while local_goal_idx < len(current_path) - 1:
                        px, py = int(current_path[local_goal_idx][0]), int(current_path[local_goal_idx][1])
                        if new_map[py, px] < 0.8:
                            clear += 1
                            if clear > 15:
                                break
                        else:
                            clear = 0
                        local_goal_idx += 1
                    
                    replanning_timer = 60 # wait for visual effect
                else:
                    rover_idx += 1
            else:
                state = "REACHED"
                add_log("DESTINATION REACHED!")
                
        elif state == "REPLANNING":
            pygame.draw.circle(screen, RED, (obs_rx, obs_ry), 6)
            pygame.draw.circle(screen, YELLOW, (obs_rx, obs_ry), 50, 1) # Sensor range pulse
            
            local_goal = current_path[local_goal_idx]
            pygame.draw.circle(screen, ORANGE, (int(local_goal[0]), int(local_goal[1])), 8)
            
            replanning_timer -= 1
            if replanning_timer <= 0:
                add_log(f"RRT targeting ({int(local_goal[0])}, {int(local_goal[1])})...")
                pygame.display.flip()
                
                local_path = rrt.plan((obs_rx, obs_ry), local_goal)
                if local_path:
                    rrt_paths.append(local_path)
                    current_path = current_path[:rover_idx] + local_path + current_path[local_goal_idx:]
                    add_log("RRT successful. Rerouting via safe path.")
                    state = "MOVING"
                else:
                    add_log("CRITICAL: RRT FAILED! No path found.")
                    state = "FAILED"
                    
        elif state == "REACHED":
            pygame.draw.circle(screen, WHITE, (rx, ry), 8)
            pygame.draw.circle(screen, GREEN, (rx, ry), 5)
            
        elif state == "FAILED":
            pygame.draw.circle(screen, RED, (rx, ry), 8)
            pygame.draw.line(screen, WHITE, (rx-5, ry-5), (rx+5, ry+5), 2)
            pygame.draw.line(screen, WHITE, (rx-5, ry+5), (rx+5, ry-5), 2)

        elif state == "BATTERY_EMPTY":
            pygame.draw.circle(screen, RED, (rx, ry), 8)
            pygame.draw.circle(screen, YELLOW, (rx, ry), 5)
            draw_text(screen, "BATTERY EMPTY", font_small, RED, cols + 15, 198)
            
        elif state == "AWAITING_TARGET":
            pygame.draw.circle(screen, MAGENTA, (rx, ry), 5) # Idle position is magenta

        pygame.display.flip()
        clock.tick(20)

    pygame.quit()

if __name__ == "__main__":
    main()
